package repository

import gormmapper "github.com/Rgss/gorm-mapper"

// global instance
var AccountRepository = &accountRepository{}

// the mapper is generated by gorm-mapper automatically
// mapper
type accountRepository struct {
	gormmapper.Mapper
}
