package repository

import gormmapper "github.com/Rgss/gorm-mapper"

// global instance
var GatewayApiRepository = &gatewayApiRepository{}

// the mapper is generated by gorm-mapper automatically
// mapper
type gatewayApiRepository struct {
	gormmapper.Mapper
}
