package repository

import gormmapper "github.com/Rgss/gorm-mapper"

// global instance
var TestRepository = &testRepository{}

// the mapper is generated by gorm-mapper automatically
// mapper
type testRepository struct {
	gormmapper.Mapper
}
