package mapper

import gormmapper "github.com/Rgss/gorm-mapper"

// global instance
var AccountMapper = &accountMapper{}

// the mapper is generated by gorm-mapper automatically
// accountMapper
type accountMapper struct {
	gormmapper.Mapper
}
