package mapper

import gormmapper "github.com/Rgss/gorm-mapper"

// global instance
var TestMapper = &testMapper{}

// the mapper is generated by gorm-mapper automatically
// testMapper
type testMapper struct {
	gormmapper.Mapper
}
