package mapper

import gormmapper "github.com/Rgss/gorm-mapper"

// global instance
var UserMapper = &userMapper{}

// the mapper is generated by gorm-mapper automatically
// userMapper
type userMapper struct {
	gormmapper.Mapper
}
